# Generated by Django 4.0.5 on 2022-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('temperature', models.CharField(max_length=20)),
                ('humidty', models.CharField(max_length=20)),
                ('gas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
