# Generated by Django 4.0.5 on 2022-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(max_length=0)),
                ('result', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(max_length=0),
        ),
    ]
