# Generated by Django 4.0.5 on 2022-06-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0002_recognition_delete_flower_alter_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognition',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
